name: 'Cache Go'
description: 'Cache Go modules'
runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - if: ${{ runner.os == 'macOS' }}
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - if: ${{ runner.os == 'Windows' }}
      uses: actions/cache@v2
      with:
        path: |
          %LocalAppData%\go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
