name: 'Cache Go'
description: 'Cache Go modules'
inputs:
  name:
    description: 'The name that is going to be used as a part of the cache keys'
    required: true
    default: 'go'
runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ inputs.name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.name }}-
    - if: ${{ runner.os == 'macOS' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ inputs.name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.name }}-
    - if: ${{ runner.os == 'Windows' }}
      uses: actions/cache@v3
      with:
        path: |
          %LocalAppData%\go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ inputs.name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.name }}-
